### ISSUE TITLE
clade fails to install on Fedora 28

### ISSUE THREAD

**Issue by evdenis** [17451k/clade#15]
Installation log:
```bash
$ sudo pip3 install -e .
WARNING: Running pip install with root privileges is generally not a good idea. Try `pip3 install --user` instead.
Obtaining file:///home/work/tmp/clade
Requirement already satisfied: ujson in /usr/local/lib64/python3.6/site-packages (from clade==1.0)
Requirement already satisfied: graphviz in /usr/local/lib/python3.6/site-packages (from clade==1.0)
Requirement already satisfied: jinja2 in /usr/local/lib64/python3.6/site-packages (from clade==1.0)
Requirement already satisfied: ply in /usr/lib/python3.6/site-packages (from clade==1.0)
Requirement already satisfied: MarkupSafe>=0.23 in /usr/local/lib64/python3.6/site-packages (from jinja2->clade==1.0)
Installing collected packages: clade
  Found existing installation: clade 1.0
    Can't uninstall 'clade'. No files were found to uninstall.
  Running setup.py develop for clade
Successfully installed clade
```

Run:
```
$ clade
Traceback (most recent call last):
  File "/usr/local/bin/clade", line 11, in <module>
    load_entry_point('clade', 'console_scripts', 'clade')()
  File "/usr/lib/python3.6/site-packages/pkg_resources/__init__.py", line 476, in load_entry_point
    return get_distribution(dist).load_entry_point(group, name)
  File "/usr/lib/python3.6/site-packages/pkg_resources/__init__.py", line 2699, in load_entry_point
    raise ImportError("Entry point %r not found" % ((group, name),))
ImportError: Entry point ('console_scripts', 'clade') not found
```

**Comment by 17451k** [comment]
Can't reproduce error on the Docker image of Fedora 28 - Clade installs and works just fine.

**Comment by 17451k** [comment]
Close due to lack of additional information and inability to reproduce the error.
