### ISSUE TITLE
Add Python 3.4 support

### ISSUE THREAD

**Issue by 17451k** [17451k/clade#20]

**Comment by 17451k** [comment]
Implemented in latest commits.

**Comment by eunovm** [comment]
Here is the exception that can be raised during installation when using Python 3.4:

```
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/home/vagrant/clade/setup.py", line 112, in <module>
        "Operating System :: Unix",
      File "/usr/lib64/python3.4/distutils/core.py", line 148, in setup
        dist.run_commands()
      File "/usr/lib64/python3.4/distutils/dist.py", line 955, in run_commands
        self.run_command(cmd)
      File "/usr/lib64/python3.4/distutils/dist.py", line 974, in run_command
        cmd_obj.run()
      File "/home/vagrant/clade/setup.py", line 40, in run
        build_libinterceptor()
      File "/home/vagrant/clade/clade/utils.py", line 84, in build_libinterceptor
        build_all(build_dir)
      File "/home/vagrant/clade/clade/utils.py", line 46, in build_all
        build_target("all", build_dir, LIBINT_SRC)
      File "/home/vagrant/clade/clade/utils.py", line 41, in build_target
        print(e.stdout)
    AttributeError: 'CalledProcessError' object has no attribute 'stdout'
```

**Comment by 17451k** [comment]
Should be fixed now.
