### ISSUE TITLE
RuntimeError: libinterceptor is not found (Fedora 29)

### ISSUE THREAD

**Issue by evdenis** [17451k/clade#59]
```
$ cat /etc/os-release | head -5
NAME=Fedora
VERSION="29 (Workstation Edition)"
ID=fedora
VERSION_ID=29
VERSION_CODENAME=""

$ pip3 install --user clade==2.2dev1
Collecting clade==2.2dev1
  Retrying (Retry(total=4, connect=None, read=None, redirect=None, status=None)) after connection broken by 'ProtocolError('Connection aborted.', OSError("(104, 'ECONNRESET')"))': /packages/0d/06/8a521367c00c99bac7486e5074d23c134d8d688802c75b9e73bc6f5ede62/clade-2.2.dev1.tar.gz
  Downloading https://files.pythonhosted.org/packages/0d/06/8a521367c00c99bac7486e5074d23c134d8d688802c75b9e73bc6f5ede62/clade-2.2.dev1.tar.gz (308kB)
    100% |████████████████████████████████| 317kB 410kB/s 
Collecting ujson (from clade==2.2dev1)
  Downloading https://files.pythonhosted.org/packages/16/c4/79f3409bc710559015464e5f49b9879430d8f87498ecdc335899732e5377/ujson-1.35.tar.gz (192kB)
    100% |████████████████████████████████| 194kB 718kB/s 
Requirement already satisfied: chardet in /usr/lib/python3.7/site-packages (from clade==2.2dev1) (3.0.4)
Collecting graphviz (from clade==2.2dev1)
  Downloading https://files.pythonhosted.org/packages/1f/e2/ef2581b5b86625657afd32030f90cf2717456c1d2b711ba074bf007c0f1a/graphviz-0.10.1-py2.py3-none-any.whl
Requirement already satisfied: ply in /usr/lib/python3.7/site-packages (from clade==2.2dev1) (3.9)
Collecting filelock (from clade==2.2dev1)
  Downloading https://files.pythonhosted.org/packages/d7/ca/3c74396a9ed8a4cfab5459800edeef9a1269591cb21f5a49bd71a49c5fa2/filelock-3.0.10-py3-none-any.whl
Installing collected packages: ujson, graphviz, filelock, clade
  Running setup.py install for ujson ... done
  Running setup.py install for clade ... done
Successfully installed clade-2.2.dev1 filelock-3.0.10 graphviz-0.10.1 ujson-1.35

$ /home/work/.local/bin/clade make
Traceback (most recent call last):
  File "/home/work/.local/bin/clade", line 11, in <module>
    load_entry_point('clade==2.2.dev1', 'console_scripts', 'clade')()
  File "/home/work/.local/lib/python3.7/site-packages/clade/extensions/cdb.py", line 120, in main
    use_wrappers=args.wrappers,
  File "/home/work/.local/lib/python3.7/site-packages/clade/intercept.py", line 36, in intercept
    i = cl(command=command, cwd=cwd, output=output, append=append, conf=conf)
  File "/home/work/.local/lib/python3.7/site-packages/clade/abstract.py", line 49, in __init__
    self.env = self._setup_env()
  File "/home/work/.local/lib/python3.7/site-packages/clade/libinterceptor.py", line 29, in _setup_env
    libinterceptor = self.__find_libinterceptor()
  File "/home/work/.local/lib/python3.7/site-packages/clade/libinterceptor.py", line 55, in __find_libinterceptor
    raise RuntimeError("libinterceptor is not found in {!r}".format(libinterceptor))
RuntimeError: libinterceptor is not found in '/home/work/.local/lib/python3.7/site-packages/clade/intercept/libinterceptor.so'
```

**Comment by 17451k** [comment]
Fixed in c826351fe20fcb739ad0159d7849ffea8a27923f and in version 2.2.dev2.
