### ISSUE TITLE
Clade changes build bases when they are accessed

### ISSUE THREAD

**Issue by eunovm** [17451k/clade#61]
This seems to be a consequence of the recent commits:
```
Raise exception:
Traceback (most recent call last):
  File "/var/lib/klever/workspace/Branches-and-Tags-Processing/src/core/core/components.py", line 427, in run
    self.main()
  File "/var/lib/klever/workspace/Branches-and-Tags-Processing/src/core/core/components.py", line 332, in callbacks_caller
    ret = attr(*args, **kwargs)
  File "/var/lib/klever/workspace/Branches-and-Tags-Processing/src/core/core/pfg/__init__.py", line 56, in generate_program_fragments
    attr_data, fragments_files = strategy.fragmentation()
  File "/var/lib/klever/workspace/Branches-and-Tags-Processing/src/core/core/pfg/fragmentation/__init__.py", line 80, in fragmentation
    deps = Program(self.logger, self.clade, self.source_paths, memory_efficient_mode=memory_efficient_mode)
  File "/var/lib/klever/workspace/Branches-and-Tags-Processing/src/core/core/pfg/abstractions/__init__.py", line 43, in __init__
    self.__divide()
  File "/var/lib/klever/workspace/Branches-and-Tags-Processing/src/core/core/pfg/abstractions/__init__.py", line 341, in __divide
    for desc in (d for d in self.clade.compilation_cmds if d.get('out') and len(d.get('out')) > 0):
  File "/usr/local/lib/python3.5/dist-packages/clade/__init__.py", line 159, in compilation_cmds
    return [self.__normalize_cmd(cmd) for cmd in cmds]
  File "/usr/local/lib/python3.5/dist-packages/clade/__init__.py", line 159, in <listcomp>
    return [self.__normalize_cmd(cmd) for cmd in cmds]
  File "/usr/local/lib/python3.5/dist-packages/clade/extensions/src_graph.py", line 74, in load_all_cmds
    compile_only=True
  File "/usr/local/lib/python3.5/dist-packages/clade/extensions/compiler.py", line 51, in load_all_cmds
    cmds = super().load_all_cmds(with_opts=with_opts, with_raw=with_raw, filter_by_pid=filter_by_pid)
  File "/usr/local/lib/python3.5/dist-packages/clade/extensions/common.py", line 181, in load_all_cmds
    cmds = self.extensions["PidGraph"].filter_cmds_by_pid(cmds)
  File "/usr/local/lib/python3.5/dist-packages/clade/extensions/pid_graph.py", line 97, in filter_cmds_by_pid
    self.update_rejected_ids(rejected_ids)
  File "/usr/local/lib/python3.5/dist-packages/clade/extensions/pid_graph.py", line 106, in update_rejected_ids
    self.dump_data(new_rejected_ids, self.rejected_ids_file)
  File "/usr/local/lib/python3.5/dist-packages/clade/extensions/abstract.py", line 179, in dump_data
    with open(file_name, "w") as fh:
PermissionError: [Errno 13] Permission denied: '/var/lib/klever/workspace/Branches-and-Tags-Processing/src/build bases/testing/fedc1e/PidGraph/rejected_ids.json'
```

**Comment by eunovm** [comment]
Although, the issue could be introduced early.

**Comment by eunovm** [comment]
Moreover, the issue can cause data races since corresponding file writes are not protected. So, it is even more crucial.

**Comment by 17451k** [comment]
Actually there is no need in saving ids of filtered commands on disk, so I removed this code in bf61691a113bd7c13c170834de722b8294398e85.

I will think about inserting debugging output there instead.
